#this datasource configuration will only work with a running(local) Docker mysql container started with "...-p 33061:3306"
spring:
  datasource:
    url: jdbc:mysql://localhost:33061/DATA?createDatabaseIfNotExist=true
    password: p4ssw0rd