spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://mysqldb:3306/DATA
    username: root
    password: test
  jackson:
    serialization:
      indent_output: true
  flyway:
    locations: classpath:db/migration
  main:
    banner-mode: off